### ISSUE TITLE
problems of Semantic segmentation

### ISSUE THREAD

**Issue by fire-2019** [valeoai/SLidR#19]
hello,I think SLIDR is an excellent job about the idea and the project. But while building this, I met a problem，I use the dataset **nuscenes v1.0-mini** , the first two steps :(1)Pre-computing the superpixels (2)Pre-training a 3D backbone is normal, but when I run 3th steps:
   python downstream.py --cfg_file="config/semseg_nuscenes.yaml" --pretraining_path="output/pretrain/[...]/model.pt"__
an ValueError occured: num_samples should be a positive integer value, but got num_samples=0
the Traceback (most recent call last) is here:
  File "/home/sjwang/study/SLidR/downstream.py", line 79, in <module>
    main()
  File "/home/sjwang/study/SLidR/downstream.py", line 59, in main
    trainer.fit(module, dm)
  File "/home/sjwang/miniconda3/envs/SLIDR/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 553, in fit
    self._run(model)
  File "/home/sjwang/miniconda3/envs/SLIDR/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 918, in _run
    self._dispatch()
  File "/home/sjwang/miniconda3/envs/SLIDR/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 986, in _dispatch
    self.accelerator.start_training(self)
  File "/home/sjwang/miniconda3/envs/SLIDR/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 92, in start_training
    self.training_type_plugin.start_training(trainer)
  File "/home/sjwang/miniconda3/envs/SLIDR/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 161, in start_training
    self._results = trainer.run_stage()
  File "/home/sjwang/miniconda3/envs/SLIDR/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 996, in run_stage
    return self._run_train()
  File "/home/sjwang/miniconda3/envs/SLIDR/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1040, in _run_train
    self.reset_train_val_dataloaders(model)
  File "/home/sjwang/miniconda3/envs/SLIDR/lib/python3.8/site-packages/pytorch_lightning/trainer/data_loading.py", line 468, in reset_train_val_dataloaders
    self.reset_train_dataloader(model)
  File "/home/sjwang/miniconda3/envs/SLIDR/lib/python3.8/site-packages/pytorch_lightning/trainer/data_loading.py", line 247, in reset_train_dataloader
    self.train_dataloader = self.request_dataloader(model, "train")
  File "/home/sjwang/miniconda3/envs/SLIDR/lib/python3.8/site-packages/pytorch_lightning/trainer/data_loading.py", line 480, in request_dataloader
    dataloader = getattr(model, f"{stage}_dataloader")()
  File "/home/sjwang/study/SLidR/downstream/lightning_datamodule.py", line 53, in train_dataloader
    return DataLoader(
  File "/home/sjwang/miniconda3/envs/SLIDR/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 266, in __init__
    sampler = RandomSampler(dataset, generator=generator)  # type: ignore
  File "/home/sjwang/miniconda3/envs/SLIDR/lib/python3.8/site-packages/torch/utils/data/sampler.py", line 103, in __init__
    raise ValueError("num_samples should be a positive integer "

I don't know whether because of the dataset,  without changing the dataset, and I change about the code :
   nusc = NuScenes(
        version="v1.0-mini", dataroot=nuscenes_path, verbose=False
    )
I have no idea about what to do next. Could you tell me how to continue my job？Thank you！！！！

**Comment by fire-2019** [comment]
now，I find it's a problem of dataset.
![图片](https://user-images.githubusercontent.com/57898579/190390137-197223f9-4404-46b4-a3f3-442eb6713d97.png)
this is my dataset, could you please show me your data structure?

**Comment by CSautier** [comment]
Hi, your dataset is fine, the problem you have is with the batch size. In the config "semseg_nuscenes.yaml" you should set the "dataset_skip_step" to 1, otherwise you only take 1% of nuscenes-mini, which is 0 sample. If that still does not solve your issue, reduce the batch_size as well, as nuscenes-mini is really small and might have less than an entire batch.
Finally keep in mind that while nuscenes-mini is useful to debug, it is too small to train anything of use.

**Comment by fire-2019** [comment]
thanks for your answer, I follow your step and the problem is solved. But I met a new trouble that say ：
  AssertionError: Table lidarseg not found
and find the problem at ：
![图片](https://user-images.githubusercontent.com/57898579/190591283-39dde204-5d8c-45ce-9897-207d2c1c2621.png)
as you say , the nuscenes-mini is enough, how to tackle this problem?
Before ask you, I dowmload nuscene-lidarseg at Web Nuscenes, but it seem no help to solve this.Could you please give me some question about this? Thank you .

**Comment by CSautier** [comment]
That is an issue you have with the dataset. Here the self.nusc is an instance of the class Nuscenes of the [nuscenes-devkit](https://github.com/nutonomy/nuscenes-devkit). The problem is probably that you don't have lidarseg in your nuscenes folder (you shoud have a lidarseg.json in v1.0-mini as well as a lidarseg folder in the nuscenes folder).
If that does not solve it, I cannot help you, I didn't write the code of nuscenes-devkit and the line you mention runs perfectly for me even with the mini set.

**Comment by fire-2019** [comment]
thanks very much for your help
